apply plugin: 'com.android.application'

Properties props = new Properties()
props.load(new FileInputStream(file("local.properties")))

android {
    signingConfigs {
        release {
            storeFile file(props['keystore.path'])
            storePassword props['keystore.password']
            keyPassword props['keystore.password']
            keyAlias = 'cipher_breaker_keystore'
        }
    }
    compileSdk 37
    defaultConfig {
        applicationId "cz.civilizacehra.cipherbreaker"
        minSdk 23
        targetSdk 37
        versionCode 17
        versionName "1.5.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
    namespace 'cz.civilizacehra.cipherbreaker'
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_19
        targetCompatibility = JavaVersion.VERSION_19
    }
}

dependencies {
    implementation 'androidx.core:core:1.19.0'
    implementation 'androidx.fragment:fragment:1.9.0'
    implementation 'com.google.android.gms:play-services-maps:20.0.0'

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0"

    testImplementation 'junit:junit:4.13.2'
}
