[project]
name = "utils"
version = "0.1.0"
description = "Tools for creating map and dictionary data"
readme = "README.md"
authors = [
    { name = "Adam Sikora", email = "adam.sikora73@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "haversine>=2.9.0",
    "osmium>=4.3.1",
    "unidecode>=1.4.0",
]

[project.scripts]
parse-osm = "map.parse_osm:main"
parse-morfflex = "cz_dict.parse_morfflex:main"

[tool.uv.build-backend]
module-name = ["map", "cz_dict", "common"]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
